[ae]
	#智能倍增时是否对样板供应器轮询分配
	#仅多个供应器有相同样板时生效，开启后请求会均分到所有可用供应器，关闭则全部分配给单一供应器
	#注意：所有相关供应器需开启智能倍增，否则可能失效
	#默认: true
	providerRoundRobinEnable = true
	#智能倍增的最大倍数（0 表示不限制）
	#此倍数是针对单次样板产出的放大倍数上限，用于限制一次推送中按倍增缩放的规模
	# Default: 0
	# Range: 0 ~ 1048576
	smartScalingMaxMultiplier = 0
	#值越大将减少AE构建合成计划过程中的 wait/notify 次数，提升吞吐但会降低调度响应性
	# Default: 100000
	# Range: > 100
	craftingPauseThreshold = 100000

[wireless]
	#无线收发器最大连接距离（单位：方块）
	#从端与主端的直线距离需小于等于该值才会建立连接。
	# Default: 256.0
	# Range: 1.0 ~ 4096.0
	wirelessMaxRange = 256.0
	#是否允许无线收发器跨维度建立连接
	#开启后，从端可连接到不同维度的主端（忽略距离限制）
	wirelessCrossDimEnable = true

[entitySpeedTicker]
	#实体加速器能量消耗基础值
	# Default: 512
	# Range: > 0
	entityTickerCost = 512
	#实体加速器黑名单：匹配的方块将不会被加速。支持通配符/正则（例如：minecraft:*）
	#格式：全名或通配符/正则字符串，例如 'minecraft:chest'、'minecraft:*'、'modid:.*_fluid'
	entityTickerBlackList = []
	#额外消耗倍率配置：为某些方块设置额外能量倍率，格式 'modid:blockid multiplier'，例如 'minecraft:chest 2x'
	#支持通配符/正则匹配（例如 'minecraft:* 2x' 会对整个命名空间生效）。
	entityTickerMultipliers = []
